
gender = 'gender'
age = 'YoB'
education = 'LoE_DI'
longitude = 'longitude'
latitude = 'latitude'
cluster = 'Cluster'
user_id = 'userid_DI'
course_id = 'course_id'
country = 'final_cc_cname_DI'
country_name = 'name'
country_longitude = 'longitude'
country_latitude = 'latitude'
instructors = 'Instructors'
grade = 'grade'
course_number = 'Course Number'
course_subject = 'Course Subject'
